### PR TITLE
add normal estimation for closed surfaces

### PR DESCRIPTION
**Pull request by RainSureZhao**
I set up a new branch and hope the commit code does not error this time.

### CODE REVIEW

**Comment by unageek** [comment]
Thank you, I'll take a look.

Could you tell me what kind of point clouds are you trying to reconstruct?

**Comment by RainSureZhao** [comment]
> Thank you, I'll take a look.
> 
> Could you tell me what kind of point clouds are you trying to reconstruct?

Hi, I am now trying to build a closed surface based on the complete point cloud data of an object. If I succeed, I will consider using incomplete point cloud data for construction later, for example, only provide 50% of the data .

**Comment by unageek** [comment]
I have implemented CC's normal orientation algorithm in #139. Could you see if it works for you? Here is an example command line:

```
./build/examples/closed_normals/closed_normals --in bunny.csv --out bunny_normals.csv
```

**Comment by RainSureZhao** [comment]
> I have implemented the CC's normal orientation algorithm in #139. Could you see if it works for you? Here is an example command line:
> 
> ```
> ./build/examples/closed_normals/closed_normals --in bunny.csv --out bunny_normals.csv
> ```

Roger that!

**Comment by RainSureZhao** [comment]
> > I have implemented the CC's normal orientation algorithm in #139. Could you see if it works for you? Here is an example command line:
> > ```
> > ./build/examples/closed_normals/closed_normals --in bunny.csv --out bunny_normals.csv
> > ```
> 
> Roger that!

Hi, When I compile on Windows, I get an error because the variable name is repeated. I replace it myself and it works.
image

**Comment by RainSureZhao** [comment]
> > I have implemented the CC's normal orientation algorithm in #139. Could you see if it works for you? Here is an example command line:
> > ```
> > ./build/examples/closed_normals/closed_normals --in bunny.csv --out bunny_normals.csv
> > ```
> 
> Roger that!

Hi, I tested it and it worked really well. Thank you very much.
image

**Comment by unageek** [comment]
Superseded by #139.

**Pull request closed without merging**
